image: alpine:latest

services:
  - docker:dind

stages:
  - build
  - tests

Code-Scan:
  stage: tests
  image: checkpoint/shiftleft:latest
  script:
    - shiftleft code-scan -s ./
  only:
    - master

Iac-Assessment:
  stage: tests
  image: checkpoint/shiftleft:latest
  script:
    - shiftleft -D iac-assessment -p ./terraform-template -r -64 -s critical
  only:
    - master

Image-Scan:
  stage: tests
  image: checkpoint/shiftleft:latest
  script:
    - shiftleft image-scan -i release/demo-app-image.tar
  only:
    - master

DockerBuild:
  stage: build
  image: docker:latest
  artifacts:
    expire_in: 2 hours
    paths:
      - release
  script:
    - docker build -t checkpoint/demo-app:latest .
    - mkdir release 
    - docker save checkpoint/demo-app:latest -o release/demo-app-image.tar
